### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by weiqiLee** [OakwoodAI/Automagica#41] opened 2018-12-20 16:31 UTC
C:\code>python app_ocr.py
Traceback (most recent call last):
  File "app_ocr.py", line 7, in <module>
    text = ExtractTextFromImage('example.jpg')
  File "C:\Python37\lib\site-packages\automagica\activities.py", line 541, in ExtractTextFromImage
    return image_to_string(Image.open(filename))
  File "C:\Python37\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Python37\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Python37\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by tvturnhout** [comment] 2018-12-20 16:31
Could you give some more info in which version of python and which OS you are using?

**Comment by weiqiLee** [comment] 2018-12-20 16:32
win10 and python3.7.1

**Comment by tvturnhout** [comment] 2018-12-20 16:32
Ok thanks, we will have a look into this.

**Comment by koenvaneijk** [comment] 2018-12-20 16:37
Did you install Tesseract as per the instructions in the `README.md`? Did you add the executable path of Tesseract to the `PATH` environment variable? The error suggests that PyTesseract cannot find the Tesseract executable.

**Comment by koenvaneijk** [comment] 2018-12-20 16:38
Keep in mind that environment variables set only apply to command lines/applications initiated after they were set. Try rebooting if all else fails to ensure proper environment variables.

**Comment by koenvaneijk** [comment] 2018-12-20 16:41
Closing this issue, as we cannot reproduce it. If the issue persists even when proper dependencies are installed and environment variables are set, please create a new issue in PyTesseracts repository describing the way to reproduce the issue.

**Closed by koenvaneijk** 2018-12-20 16:41 UTC
