### ISSUE TITLE
same script on multiple bots

### ISSUE THREAD

**Issue by garanews** [OakwoodAI/Automagica#92] opened 2020-01-27 09:49 UTC
I am not able to run same script on 2 bots.
From the configuration page it seems should be possible:
![image](https://user-images.githubusercontent.com/16938405/73164633-96884e00-40f2-11ea-916f-2723723f51fd.png)
If I create 2 scripts assigning single bot each, both bots will work.
Any help?

**Comment by koenvaneijk** [comment] 2020-01-30 09:33
@garanews do I understand it correctly that you have the following case:

Bot A
Bot B

Script A
Script B

Bot A is assigned to Script A
Bot B is assigned to Script B

If you run script B n times, both Bot A and Bot B will perform the script? This should not happend in a normal situation and is not intended.

**Comment by garanews** [comment] 2020-01-30 11:05
I have
BOT A
BOT B
.
BOT N

and Script A that I need to execute on BOT A, BOT B ,... BOT N

And I don't want load on portal
SCRIPT A = SCRIPT B = .... = SCRIPT N
And then assign
SCRIPT A to BOT A 
SCRIPT B to BOT B 
SCRIPT N to BOT N

I don't know if it is a bug, because portal permit to assign same script on all bots you wants, and this in my case is not working: the script is executed only on the first bot listed.

**Comment by koenvaneijk** [comment] 2020-02-13 07:04
The distribution of jobs among bots is random in the sense that if you assign a group of bots to the same script and start multiple jobs, the bots will pick up jobs one by one.

After much testing, we are confident this is working as intended and is not a bug.

Kind regards,
Koen
Automagica.com

**Closed by koenvaneijk** 2020-02-13 07:04 UTC
